erichelgeson/BlueSCSI

.github/workflows/main.yml

A Github Action workflow (based on https://docs.platformio.org/en/latest/integration/ci/github-actions.html) that automatically builds the project for all devices listed in platformio.ini.
Not a big deal right now, but will be helpful in the future when we have more than one target device or arch.

Add Github Action workflow that ensures the project compiles

---

src/BlueSCSI.cpp

Uses a teensy bit less flash, same memory footprint:
```
RAM:   [====      ]  42.9% (used 8784 bytes from 20480 bytes)
Flash: [========  ]  81.0% (used 53076 bytes from 65536 bytes)
RAM:   [====      ]  42.9% (used 8784 bytes from 20480 bytes)
Flash: [========  ]  81.0% (used 53052 bytes from 65536 bytes)
```

Use `gpio_read` to toggle led state, saves 24 bytes of flash.

---

src/BlueSCSI.cpp

Optimize the selected SCSI ID code to use __builtin_clz to find the first selected bit. This compiles to the ARM CLZ instruction, which is supported on the STM32F103.

CLZ optimization

---

src/BlueSCSI.cpp

For your consideration, here is an optimization of reset handling.
Rather than polling m_isBusReset all over the place, I've changed the code to set up longjmp that can be used for a bus reset, then added the necessary code to call that from the interrupt handler. That does require a little bit of assembly.
I've gated the reset handling so it doesn't fire in the middle of a read, write, or flush of the image file. Flush will also be called now if there is a reset while a write was in progress.
I'm seeing about a 5% increase in read speed, and 10% increase in write speed on the computer I'm testing this on (Quadra 650, Apple drivers, Hyundai SD card, SCSI Director).
BTW, removed the PIN_MAP from attachInterrupt(). It was working OK because the value returned from PIN_MAP was the same, but …

Optimize handling of reset interrupt.

---

platformio.ini
src/BlueSCSI.cpp

I've switched to the latest toolchain. It works great, the read speed was unchanged. The newer compiler is producing slightly better code for writing (readDataLoop function), and with a slight adjustment to the timing, that is benchmarking a fraction faster.
I got these benchmark results:
LC III+: Read 1234 KB/sec, write 861 KB/sec (was 848 KB/sec with old toolchain)
Quadra 650: Read 1143 KB/sec, write 1162 KB/sec (was 950 KB/sec)
PowerMac 7100/80: Read 1266 KB/sec, write 1273 KB/sec (was 1253 KB/sec)
PowerMac G3/266: Read 1273 KB/sec, write 1307 KB/sec (was 1286 KB/sec)

Switch to latest toolchain

---

src/BlueSCSI.cpp

Apple HD SD Setup support seemed to require 3 things:
Mode page 0x30 support with Apple's identifier.
Support for Mode Select, it just needs to not return an error.
Support for Verify, it just needs to not return an error.
Support for Verify might also help with FWB HDT. It's diagnostics tool was definitely complaining about Verify commands failing.
I've also done a little bit of cleanup around SCSI error handling and block range checking. Another change I made is adding support for Mode Sense with the Changeable Values page control option so that it returns zeros (not changeable). Not aware of anything that actually needs these changes, other than when using tools like Sedit or HDT World Control.

Apple HD SC Setup support

---

.vscode/extensions.json
src/BlueSCSI.cpp

Allow for BlueSCSI to load image sets without having to move files around on the SD card. As an example this will allow users to use the same BlueSCSI and switch between their Mac Plus, PowerMac, PowerBook, etc without having to remove the SD card and change/move files.
Using Pins A1/B1 and the internal pullup, check at startup and load the appropriate `ImageSetN` folder. Default is to load the root of the SD card so there is no breaking behavior. 
If the optional `/ImageSetAll` directory exists - it will always load images in there. This way you can have a shared drive between all sets.
If an ID conflicts, the last one wins. Order is `ImageSetN`, then `ImageSetAll`.
| A1 | B1 | # |
|-|-|-|
| H  | H  | default `/` or `/ImageSet0` if exists |
| L  | H  | `/ImageSet1`|
| H  | L  | …

Image set selection

---

src/BlueSCSI.cpp

This is code cleanup around SCSI phase changes, and a couple of delays added to meet the 400ns bus settle delays in the SCSI specifications. Timing was measured on an oscilloscope.
I'm not seeing any performance impact, positive or negative, which is expected. I measured the time to receive a 10 byte command from an LC III+ at around 160us. I think that is mostly the BlueSCSI waiting on the Mac, so adding small delays didn't seem to make any difference to performance.
Tested on an LC III+ and a Quadra 650.
One thing I will note, I removed this line of code in messaging out handling:
memset(m_msb, 0x00, sizeof(m_msb));
Clearing the whole 2K buffer like that seemed unnecessary, and takes about 4us. That definitely stood out on the scope, but only impacts initiators that have a message out …

Cleanup of SCSI phase change code, and adjustment of bus settle delays.

---

src/BlueSCSI.cpp

Instruction alignment and pipelining is complicated, I still don't fully understand why the first nop this adds makes things faster.
The second nop change is to add an extra cycle, as the 2 prior instructions (mvn and strb) seem to be pipelining together so the code only had 4 cycles between setting REQ and waiting for ACK.
I'm seeing about a 5% to 7% increase in write speed measured with SCSI Director:
Mac LC III+: Was 865 now 926
Quadra 650: Was 1175 now 1234
PowerMac 7100/80: Was 1280 now 1350

Write speed tuning

---

src/BlueSCSI.cpp

Changed the file position calculation to 64bit to handle image files larger than 4GB.
I tested this with Sedit. Before this change, sectors are aliasing every 4GB (0x80000 blocks). Reading block 0x800000 is the same as block 0, and writing to block 0x800000 overwrites block 0. After this change, everything works as expected.
In a quick test on an LC III+, I did notice a very small performance regression, maybe 1-2%, which I was not expecting. This calculation is only done once per transfer, and the STM32F103 has hardware support for long multiply (umull), so I wouldn't expect these code changes to have a direct impact on performance. I'm guessing there is some sort of alignment sensitivity in writeDataPhaseSD and readDataPhaseSD. Haven't had a chance to investigate that yet.

Support for image files larger than 4GB

---

platformio.ini

Got a few APM32F103C8T6 clones. Unfortunately(and oddly) they were rebadged to STM32 - I'm not sure why because the APM32 seems to perform better! The easy way to tell is if you get a chip (even if it has a STM badge on it) and it shows 256kb - It's likely one of these chips. The other behavior is they are unstable at the stock 72MHz - but run fine at 96-128MHz.
This PR adds a profile to build a bin for this chip, the only change is to set the clock to 96MHz.
Link to data sheet.
http://apexsemi.geehy.com/uploads/tool/APM32F103x4x6x8xB%C2%A0Datasheet%C2%A0V1.2.pdf

Add support for the APM32F103C8T6 chip, a clone of the STM32F103

---

platformio.ini
src/BlueSCSI.cpp

Fix default env name, remove tabs.

Minor fixes

---

platformio.ini
src/BlueSCSI.cpp
src/scsi_mode.h
src/scsi_sense.h

Thanks to @marcelv-3 for the code for SCSI Read & Write Buffer.
Trivial impl of ReZero Unit & Send Diagnostic

Four new commands & some Sense

---

src/BlueSCSI.cpp

I noticed the XCVR changes had TRANSCEIVER_IO_SET(vTR_DBP,TR_OUTPUT) in the writeDataLoop. That results in it happening every block, rather than once per transfer, and probably messes up the code alignment potentially impacting performance.
Matching code to set the transceivers back to input also seemed to be missing. It might not actually matter, as typically commands will be followed by a status output (SCSI_DB_INPUT() might also not matter for the same reason), but that would require further investigation.
I don't have the XCVR hardware to test this change.

XCVR code cleanup

---

src/BlueSCSI.cpp

Trivial impl, not much we can reply with here.

Implement Read Defect Data 0x37

---

src/BlueSCSI.cpp
src/BlueSCSI.h

SCSI device state is now per device instead of global

Switched to function table for SCSI commands

---

src/BlueSCSI.cpp
src/scsi_sense.h

Resolves an issue with SCSI Director 4 requesting this page.

Add Sense page for caching 0x08

---

src/BlueSCSI.cpp

Still compatible with Apple formatting utils

Change product so vendor specific Quantum commands are not issued

---

platformio.ini

Allow CI to run.
2.2.0 has a lot of changes, need to go through them.

Pin SdFat to 2.0.6

---

src/BlueSCSI.h

32 char limit existed in SDFat 1.x I believe, but no longer does in SDFat 2.x

Allow for file names to be up to 64 chars

---

src/BlueSCSI.cpp

This reverts commit 1cfaf005943342fdeddb2c5fe9626953a0b502a1.
We can actually run at any SPI speed - some cards run fine at 49 that wont run at 50. Our assumption about how the divisor worked was incorrect and we'd slow the SPI bus too much for no reason.
Removed the warning to the user too - a 25MHz SPI is plenty fast here. Need to still update the troubleshooting docs to take the info in the Slow SPI article into account.

Revert "We only need to test 50 and 25 as the rest are just divided and rounded to full and half."

---

src/BlueSCSI.cpp

See: https://github.com/greiman/SdFat/issues/256#issuecomment-778795554
- performance can be impacted if the file is fragmented on the SD card.

Warn user if file is fragmented

---

src/BlueSCSI.cpp

While looking in to another issue, I discovered that debug builds were broken due to a variable only being defined in a later conditional. This change moves it back up to a common point where it is a available for all debugging output

Ensure allocLength is defined when needed in onReadBuffer

---

platformio.ini
src/BlueSCSI.h

- Fix syntax of a cast to a uint32
- Remove defines that are already made by the base platform
Cleans up platform.io compile output quite a bit, making it much easier to spot other errors/warnings, of which there is still one, but I'm not sure if it's legitimate, and if so, how to fix it:
```
src/BlueSCSI.cpp: In function 'void longjmpFromInterrupt(int*, int)':
src/BlueSCSI.cpp:790:1: warning: 'noreturn' function does return
790 | }
| ^
```

Fix some compiler warnings

---

src/BlueSCSI.cpp
src/BlueSCSI.h

I've got a BluePill with slightly different pins in use for the internal LED and PA0, and in trying to change them, I wanted an easier way to do so in the defines.
Switched from setting the GPIO register directly to using gpio_write, which does add 104 bytes or so

Easier to change LEDs

---

src/BlueSCSI.cpp
src/BlueSCSI.h

This PR is mainly focused on cleaner/more informative logging, keeping information grouped with the section/file it belongs with.
The PR also endeavours to make better use of constants and macros, and use a consistent convention around char array lengths. There's also some light whitespace cleanup and fixing of a few typos.
The largest functional change in the PR is the change from `finalizeFileLog` to `finalizeDevices`. This function now contains the call to `readSCSIDeviceConfig` in the case that two files are defined with the same ID, so that it is only called once, and the function now also outputs the filename that is being served for the ID to make absolutely clear on what IDs the drive image should be appearing.
This PR doesn't make any changes to anything that runs in the loop, so …

Reformatted Logging
